services:
  vote:
    image: tupychka.azurecr.io/vote:latest

  result:
    image: tupychka.azurecr.io/result:latest

  worker:
    image: tupychka.azurecr.io/worker:latest

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
